name = "sleep-dashboard-api"
main = "src/index.js"
compatibility_date = "2026-01-01"

# Variables p√∫blicas (NO secrets)
[vars]
ALLOWED_ORIGIN = "https://sleep-dashboard-v4.pages.dev"
DEFAULT_COUNTRY = "PE"
DEFAULT_TIMEZONE = "America/Lima"
DEFAULT_REQUIRED_SCHEDULE = "MON_FRI"
DEFAULT_EXCLUDE_HOLIDAYS = "1"
MIN_SLEEP_MINUTES = "345"

# D1 binding
[[d1_databases]]
binding = "DB"
database_name = "sleep_db"
database_id = "b05c3d3f-ef5a-40fa-8785-5d5cc77ffd45"

# (Opcional) R2 a futuro
# [[r2_buckets]]
# binding = "R2"
# bucket_name = "sleep-media"
